name: aur-publish

on:
  push:
    tags:
      - 'v*'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: AUR package publisher
        uses: BarbUk/aur-publish-docker-action@v1.0.3
        with:
          package_name: snippy-snippet
          commit_username: 'BarbUk'
          commit_email: ${{ secrets.AUR_SSH_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
