name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
jobs:
  release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Update version in file
        run: |
          echo "updating version with: ${GITHUB_REF_NAME}"
          sed --in-place --regexp-extended --expression "s/(readonly version=).*$/\1${GITHUB_REF_NAME}/" snippy
      - name: Create Release
        run: |
          gh release create --generate-notes --verify-tag "${GITHUB_REF#refs/*/}" -t "${GITHUB_REF#refs/*/}" --draft snippy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  aur-publish:
    name: Publish release
    needs: release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: AUR package publisher
        uses: BarbUk/aur-publish-docker-action@3f63d436d0b4926cf1ede8cea1d5eff95782bc71 # v1.0.8
        with:
          package_name: snippy-snippet
          commit_username: 'BarbUk'
          commit_email: ${{ secrets.AUR_SSH_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
